services:
  web:
    volumes:
      - ./UserManagemenService:/app/UserManagemenService
      # - ./.:/app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5154:5154"
  
