FROM mcr.microsoft.com/dotnet/sdk:8.0

# install dependencies
RUN apt-get update -y && apt-get install -y inotify-tools \
  && apt-get clean && rm -f /var/lib/apt/lists/*_*
  
RUN dotnet tool install --global dotnet-ef

ENV APP_HOME /app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

ENTRYPOINT ["/bin/sh", "-c", "dotnet watch --project UserManagemenService/UserManagemenService.csproj run"]