services:
  web:
    volumes:
      - ./UserManagemenService/appsettings.Development.json:/app/UserManagemenService/appsettings.Development.json
      - ./UserManagemenService/appsettings.json:/app/UserManagemenService/appsettings.json
      - ./UserManagemenService/Controllers:/app/UserManagemenService/Controllers
      - ./UserManagemenService/DAL:/app/UserManagemenService/DAL
      - ./UserManagemenService/DTO:/app/UserManagemenService/DTO
      - ./UserManagemenService/Migrations:/app/UserManagemenService/Migrations
      - ./UserManagemenService/Models:/app/UserManagemenService/Models
      - ./UserManagemenService/Program.cs:/app/UserManagemenService/Program.cs
      - ./UserManagemenService/Properties:/app/UserManagemenService/Properties
      - ./UserManagemenService/UserManagemenService.csproj:/app/UserManagemenService/UserManagemenService.csproj
      - ./UserManagemenService/UserManagemenService.http:/app/UserManagemenService/UserManagemenService.http
      - ./UserManagemenService.Tests/Integration:/app/UserManagemenService.Tests/Integration
      - ./UserManagemenService.Tests/DatabaseFixture.cs:/app/UserManagemenService.Tests/DatabaseFixture.cs
      - ./UserManagemenService.Tests/UserManagemenService.Tests.csproj:/app/UserManagemenService.Tests/UserManagemenService.Tests.csproj
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5154:5154"
    environment:
      ASPNETCORE_CONNECTION_STRING: "Host=db_dev;Database=postgres_dev;Username=test_user;Password=test_password"

  db_dev:
    image: "postgres:15.4-alpine3.17"
    ports:
      - 8004:5432
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: postgres_dev
