FROM mcr.microsoft.com/dotnet/sdk:8.0

# RUN apk update

# RUN apk add --no-cache \
#   git \
#   inotify-tools \
#   build-base

ENV APP_HOME /app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

ENTRYPOINT ["dotnet", "watch" ,"--project", "UserManagemenService/UserManagemenService.csproj" , "run"]
